export const languageMapping = {
  "fr-ca": "Français (Canada)",
  da: "Dansk",
  "zh-tw": "中文(台灣)",
  "pt-br": "Português (Brasil)",
  uk: "Українська",
  lt: "Lietuvių",
  th: "ภาษาไทย",
  fi: "Suomi",
  ro: "Română",
  is: "Íslenska",
  en: "English (US)",
  "es-la": "Español (América Latina)",
  el: "Ελληνικά",
  hi: "हिन्दी",
  hu: "Magyar",
  fr: "Français (France)",
  it: "Italiano",
  ko: "한국어",
  bg: "Български",
  cz: "Čeština",
  sk: "Slovenčina",
  pt: "Português (Portugal)",
  "en-gb": "English (UK)",
  sv: "Svenska",
  id: "Bahasa Indonesia",
  de: "Deutsch",
  ms: "Bahasa Melayu",
  vi: "Tiếng Việt",
  zh: "中文(简体)",
  es: "Español (España)",
  sr: "Српски",
  ar: "‏العربية‏",
  he: "‏עברית‏",
  nl: "Nederlands",
  no: "Norsk",
  pl: "Polski",
  ja: "日本語",
  ru: "Русский",
  tr: "Türkçe",
};
